### ISSUE TITLE
uni-app 样式不生效问题

### ISSUE THREAD

**Issue by EmiyaGm** [EmiyaGm/blog#31]
## 问题说明
h5 上使用了 video 标签当做直播的播放器，然后想通过 scss 修改样式，于是就有了这样一段代码

```scss
.myvideo {
  video {
    object-fit: fill;
  }
}
```

结果发现并不能生效，一开始以为是样式穿透的问题，尝试加了 deep 后发现并没有解决。也尝试在最外层样式中直接写

```scss
video {
  object-fit: fill;
}
```

也并不生效
最后想到 uni-app 要考虑h5和app共同的样式，所以肯定会对css做重新编译，以便于适应双端的样式，这才发现 `video` 标签会被处理成 uni-video 标签，在 uni-app 中使用 video 组件，本质上是用 uni-video 组件，因为要兼容双端

```scss
video {
  object-fit: fill;
}

// 编译后
uni-vide {
  object-fit: fill;
  -o-object-fit: fill;
}
```
